# Generated by Django 5.0.2 on 2024-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_organizationsettings_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='brand',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.JSONField(default=dict),
        ),
    ]
