from django.urls import path, include
from kalvi.api.views import SignInEndPoint, SignUpEndPoint, UserProfileView, UserChangePasswordView, SendPasswordResetEmailView, UserPasswordResetView, SignOutEndpoint, TokenRefreshView, MagicGenerateEndpoint, MagicSignInEndpoint
from db.Oauth.views import GoogleSocialAuthView, GithubSocialAuthView
from db.views import ProfileAPIView, OrganizationSettingsAPIView

urlpatterns = [
    path(
        "common/sign-up/",
        SignUpEndPoint.as_view(),
        name="kalvi-sign-up",
    ),
    path(
        "common/sign-in/",
        SignInEndPoint.as_view(),
        name="kalvi-sign-in",
    ),
    path(
        "common/user/",
        UserProfileView.as_view(),
        name="user-detail",
    ),
    path(
        "common/update-password/",
        UserChangePasswordView.as_view(),
        name="password-update",
    ),
    path(
        "common/send-reset-password-email/",
        SendPasswordResetEmailView.as_view(),
        name="send-reset-email",
    ),
    path(
        "common/reset-password/<str:uid>/<str:token>/",
        UserPasswordResetView.as_view(),
        name="reset-password-through-mail",
    ),
    path(
        "common/google/auth/",
        GoogleSocialAuthView.as_view(),
        name="google-sign-in"
    ),
    path(
        "common/github/auth/",
        GithubSocialAuthView.as_view(),
        name="github-sign-in"
    ),
    path('common/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    path("common/sign-out/",
        SignOutEndpoint.as_view(),
        name="sign-out"
    ),
    path(
        "common/magic-generate/",
        MagicGenerateEndpoint.as_view(),
        name="magic-generate",
    ),
    path(
        "common/magic-sign-in/",
        MagicSignInEndpoint.as_view(),
        name="magic-sign-in"
    ),
    path(
        'common/profile/',
        ProfileAPIView.as_view(),
        name='profile'
    ),
    path('admin/organization-settings/',
        OrganizationSettingsAPIView.as_view(),
        name='organization-settings')
]
