import type { Metadata } from "next";
import "@repo/tailwind-config/css";
import { ApplicationLayout } from "@repo/ui/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApplicationLayout>{children}</ApplicationLayout>
    </html>
  );
}
